@startuml
class gui.SkillButton {
- Skill skill
- Button btn
- Text cooldownText
- ImageView iconView
- boolean isOwnerTurn
- GameManager gameManager
+ void updateUI()
+ void setTurnActive(boolean)
+ void onTurnStart()
}


abstract class logic.skills.Skill {
# String name
# Image icon
# int maxCooldown
# int currentCooldown
# boolean isActive
+ {abstract}void activate(GameManager)
+ void reduceCooldown()
+ void use(GameManager)
+ boolean isReady()
+ Image getIcon()
+ int getCurrentCooldown()
+ String getName()
}


class entity.playerunit.Carrot {
- {static} Image NORMAL_IMG
- {static} Image ATTACK_IMG
- {static} Image DAMAGED_IMG
- {static} Image PROJECTILE_IMG
- boolean isStunShot
+ void render(GraphicsContext)
+ void stunShot()
+ void doubleDamage()
+ void resetBuffs()
+ Image getProjectileImage()
+ double getLaunchX()
+ double getLaunchY()
+ double getLaunchAngle()
+ boolean isPoisonShot()
+ boolean isStunShot()
}


class logic.skills.Stun {
+ void activate(GameManager)
}

enum logic.enums.PlayerTurn {
+  PLAYER_ONE
+  PLAYER_TWO
}

class logic.mechanics.TurnTimer {
- double maxTime
- double currentTime
- boolean isTimeOut
+ void tick(double)
+ void reset()
+ int getCurrentTimeInt()
+ boolean isTimeOut()
}


class logic.GameLoop {
- GameManager gameManager
- GamePane gamePane
- PlayerStatusPane playerStatusPane
- ArrayList<GameObject> allObjects
- long lastNanoTime
+ void handle(long)
}


class logic.skills.Growth {
+ void activate(GameManager)
}

class gui.MainMenu {
- Runnable onHowToAction
- Runnable onStartAction
+ void setOnHowToAction(Runnable)
+ void setOnStartAction(Runnable)
}


class logic.skills.Shield {
+ void activate(GameManager)
}

class logic.managers.EntityManager {
- Carrot carrot
- Onion onion
- Wall wall
- ArrayList<GameObject> allObjects
+ void initializeGameWorld(boolean)
+ Carrot getCarrot()
+ Onion getOnion()
+ Wall getWall()
+ ArrayList<GameObject> getAllObjects()
+ void addProjectile(Projectile)
+ void cleanupDestroyed(Projectile)
}


class logic.skills.Double {
+ void activate(GameManager)
}

class logic.skills.Heal {
+ void activate(GameManager)
}

class gui.ModeSelectMenu {
- Runnable onDoomedAction
- Runnable onClassicAction
+ void setOnDoomedAction(Runnable)
+ void setOnClassicAction(Runnable)
}


class gui.CustomHpBar {
- Rectangle bar
- Rectangle bg
- double maxWidth
- Timeline smoothAnim
+ void setHp(double)
+ void setRightSide()
}


class gui.IntroMenu {
- Runnable onAction
+ void setOnAction(Runnable)
}


class entity.status.ToxicStatus {
- double damagePerTurn
- boolean isFresh
+ void activate(Character)
}


class gui.HowToMenu {
- Runnable onStartAction
+ void setOnStartAction(Runnable)
- VBox SkillDescription(String,String)
}


class logic.handlers.CollisionHandler {
- TurnManager turnManager
+ long handleCollision(Projectile,Character,Wall)
}


class entity.status.ShieldStatus {
- double damageReduction
+ void activate(Character)
+ double getDamageReduction()
}


class logic.managers.TurnManager {
- PlayerTurn currentPlayerTurn
- TurnState currentTurnState
- TurnTimer turnTimer
- Wind wind
- int lastSecondPlayed
+ void update(double)
+ void switchTurn()
+ void reset()
+ void forceEndTurn()
+ PlayerTurn getCurrentPlayerTurn()
+ TurnState getCurrentTurnState()
+ void setCurrentTurnState(TurnState)
+ Wind getWind()
+ TurnTimer getTurnTimer()
}


class entity.status.StunStatus {
+ void activate(Character)
+ boolean shouldSkipTurn()
}

class gui.PlayerStatusPane {
- CustomHpBar onionHpBar
- CustomHpBar carrotHpBar
- Carrot carrot
- Onion onion
- HBox p1SkillBox
- HBox p2SkillBox
- VBox p1StatusBox
- VBox p2StatusBox
+ void update()
+ void setSkills(SkillButton,SkillButton,SkillButton,SkillButton,SkillButton,SkillButton)
- void updateStatusIcons(VBox,entity.base.Character)
}


abstract class entity.base.GameObject {
# double width
# double height
# double x
# double y
+ {abstract}Rectangle2D getHitBox()
+ boolean isIntersects(GameObject)
+ {abstract}void update(double)
+ {abstract}void render(GraphicsContext)
+ double getWidth()
+ void setWidth(double)
+ double getY()
+ void setY(double)
+ double getX()
+ void setX(double)
+ double getHeight()
+ void setHeight(double)
}


class logic.handlers.InputHandler {
- GameManager gameManager
+ void attachEventHandlers(Scene)
+ void handleMousePressed(MouseButton,double,double)
+ void handleMouseReleased(MouseButton)
}


class logic.managers.SceneManager {
- StackPane root
- GameManager gameManager
- IntroMenu introMenu
- MainMenu mainMenu
- HowToMenu howToMenu
- ModeSelectMenu modeSelectMenu
- ImageCursor carrotCursor
- ImageCursor onionCursor
- void initializeMenus()
- void initializeCursors()
+ void showIntroMenu()
- void showMainMenu()
- void showHowToMenu()
- void showModeSelectMenu()
+ void showGameScene(GamePane,PlayerStatusPane,PowerBarPane,TurnInfoPane)
+ void showGameOverWindow(String)
+ void updateCursor(PlayerTurn)
}


abstract class entity.base.StatusEffect {
# int duration
# Image icon
+ void onTurnStart(Character)
+ {abstract}void activate(Character)
+ boolean isFinished()
+ Image getIcon()
}


class util.UIButton {
+ {static} StackPane SignButton(String,String,Runnable)
}

class gui.PowerBarPane {
- GameManager gameManager
- Rectangle bg
- Rectangle fg
- double BAR_WIDTH
- double BAR_HEIGHT
- double Y_OFFSET
+ void update(Character)
}


enum logic.enums.TurnState {
+  READY
+  CHARGING
+  PROJECTILE_IN_AIR
+  CHANGING_TURN
+  HIT
}

interface entity.base.Damagedable {
~ void takeDamage(double)
}

class gui.GamePane {
- Canvas canvas
- ArrayList<GameObject> allObjects
- GraphicsContext gc
+ void drawObjects()
}


class entity.unit.Wall {
+ Rectangle2D getHitBox()
+ void update(double)
+ void render(GraphicsContext)
}

class entity.unit.ProjectileStats {
- double damage
- double scale
- boolean isPoisonous
- boolean isStun
- int poisonDuration
- double poisonDamage
+ double getDamage()
+ double getScale()
+ boolean isPoisonous()
+ boolean isStun()
+ int getPoisonDuration()
+ double getPoisonDamage()
}


abstract class entity.base.Character {
# double hp
# double maxHp
# boolean isDead
- {static} double DAMAGED_STATE_DURATION_S
- double damagedStateTimer
# boolean isAttacking
# double damageMultiplier
# double projectileScale
- ArrayList<StatusEffect> activeStatusEffects
+ void takeDamage(double)
+ Rectangle2D getHitBox()
+ void update(double)
+ void heal(int)
+ void toxic()
+ void stunShot()
+ void doubleDamage()
+ void growth()
+ void resetBuffs()
+ void addStatusEffect(StatusEffect)
+ boolean checkTurnStatus()
+ Projectile shoot(double,Wind,boolean)
+ {abstract}double getLaunchX()
+ {abstract}double getLaunchY()
+ {abstract}double getLaunchAngle()
+ {abstract}Image getProjectileImage()
+ {abstract}boolean isPoisonShot()
+ {abstract}boolean isStunShot()
+ double getHp()
+ void setHp(double)
+ double getMaxHp()
+ void setDead(double)
+ boolean isDead()
+ double getDamageMultiplier()
+ double getProjectileScale()
+ void setAttacking(boolean)
+ boolean isShowingDamaged()
+ ArrayList<StatusEffect> getActiveStatusEffects()
}


class logic.managers.SoundManager {
- {static} AudioClip throwingSound
- {static} AudioClip strikeSound
- {static} AudioClip skillUsedSound
- {static} AudioClip tickingSound
- {static} AudioClip clickSound
- {static} AudioClip hoverSound
- {static} MediaPlayer bgmPlayer
+ {static} void playThrowSound()
+ {static} void playStrikeSound()
+ {static} void playSkillSound()
+ {static} void playTickingSound()
+ {static} void playClickSound()
+ {static} void playHoverSound()
+ {static} void playBackgroundMusic()
}


class logic.mechanics.Wind {
- double strength
- double MAX_STRENGTH
- Random random
- int duration
+ void onNewRound()
- void randomize()
+ double getStrength()
+ int getDirection()
+ double getStrengthMagnitude()
+ int getRemainingDuration()
}


class application.Main {
+ void start(Stage)
+ {static} void main(String[])
}

class logic.managers.SkillManager {
- GameManager gameManager
- PlayerStatusPane playerStatusPane
- SkillButton p1Skill1
- SkillButton p2Skill1
+ void initializeSkills()
+ void updateSkillButtons(PlayerTurn,boolean)
+ void disableAllSkills()
+ void handleSkillUsage(PlayerTurn)
}


class entity.unit.Projectile {
- {static} double GRAVITY
- Image image
- double vx
- double vy
- double initialVx
- boolean isDestroyed
- double angleRotation
- double spinSpeed
- {static} double DEFAULT_HITBOX
- ProjectileStats stats
- Wind wind
+ Rectangle2D getHitBox()
+ boolean isIntersects(GameObject)
+ void update(double)
+ void render(GraphicsContext)
+ double getDamage()
+ int getPoisonDuration()
+ boolean isStun()
+ boolean isPoisonous()
+ double getPoisonDamage()
+ boolean isDestroyed()
+ void setDestroyed(boolean)
}


class logic.mechanics.PowerMechanic {
- double currentPower
- double MAX_POWER
- double MIN_POWER
- double POWER_CHARGE_RATE
+ void reset()
+ void charge(double)
+ double getCurrentPower()
+ double getMaxPower()
+ double getMinPower()
}


class gui.GameOverPane {
- Runnable onRestart
- Runnable onExit
+ void setOnRestart(Runnable)
+ void setOnExit(Runnable)
}


class logic.skills.Toxic {
+ void activate(GameManager)
}

class logic.GameManager {
+ boolean isGameOver
- StackPane root
- SceneManager sceneManager
- TurnManager turnManager
- EntityManager entityManager
- PowerMechanic powerMechanic
- CollisionHandler collisionHandler
- SkillManager skillManager
- PlayerStatusPane playerStatusPane
- PowerBarPane powerBarPane
- Canvas gameCanvas
- Projectile currentProjectile
- long hitTimestamp
- TurnInfoPane turnInfoPane
- ImageCursor carrotCursor
- ImageCursor onionCursor
- InputHandler inputHandler
- boolean isDoomedMode
+ void start()
+ void startGame()
- void setupInputHandlers()
+ void launchProjectile()
+ void update(double)
- void switchTurn()
+ void checkGameOver()
+ void showGameOverWindow()
- void updateCursor()
+ void setDoomedMode(boolean)
+ Character getActivePlayer()
+ TurnState getCurrentTurnState()
+ double getCurrentPower()
+ double getMaxPower()
+ double getMinPower()
+ void setCurrentTurnState(TurnState)
+ TurnManager getTurnManager()
+ PowerMechanic getPowerMechanic()
+ boolean isDoomedMode()
+ void handleSkillUsage()
}


class entity.playerunit.Onion {
- {static} Image NORMAL_IMG
- {static} Image ATTACK_IMG
- {static} Image DAMAGED_IMG
- {static} Image PROJECTILE_IMG
- boolean isPoisonShot
+ void render(GraphicsContext)
+ void takeDamage(double)
+ void toxic()
+ void growth()
+ void resetBuffs()
+ Image getProjectileImage()
+ double getLaunchX()
+ double getLaunchY()
+ double getLaunchAngle()
+ boolean isPoisonShot()
+ boolean isStunShot()
}


class gui.TurnInfoPane {
- Text turnText
- Text timerText
- Rectangle windBar
- ImageView windArrow
- StackPane windBarContainer
- double MAX_WIND_BAR_WIDTH
- double MAX_WIND_STRENGTH
- int lastWindDirection
+ void updateUI(int,PlayerTurn,Wind)
}




javafx.scene.layout.StackPane <|-- gui.SkillButton
entity.base.Character <|-- entity.playerunit.Carrot
logic.skills.Skill <|-- logic.skills.Stun
javafx.animation.AnimationTimer <|-- logic.GameLoop
logic.skills.Skill <|-- logic.skills.Growth
gui.VBox <|-- gui.MainMenu
logic.skills.Skill <|-- logic.skills.Shield
logic.skills.Skill <|-- logic.skills.Double
logic.skills.Skill <|-- logic.skills.Heal
gui.VBox <|-- gui.ModeSelectMenu
javafx.scene.layout.StackPane <|-- gui.CustomHpBar
gui.VBox <|-- gui.IntroMenu
entity.base.StatusEffect <|-- entity.status.ToxicStatus
gui.VBox <|-- gui.HowToMenu
entity.base.StatusEffect <|-- entity.status.ShieldStatus
entity.base.StatusEffect <|-- entity.status.StunStatus
javafx.scene.layout.Pane <|-- gui.PlayerStatusPane
javafx.scene.layout.Pane <|-- gui.PowerBarPane
gui.StackPane <|-- gui.GamePane
entity.base.GameObject <|-- entity.unit.Wall
entity.base.Damagedable <|.. entity.base.Character
entity.base.GameObject <|-- entity.base.Character
javafx.application.Application <|-- application.Main
entity.base.GameObject <|-- entity.unit.Projectile
javafx.scene.layout.StackPane <|-- gui.GameOverPane
logic.skills.Skill <|-- logic.skills.Toxic
entity.base.Character <|-- entity.playerunit.Onion
javafx.scene.layout.VBox <|-- gui.TurnInfoPane
@enduml